### ISSUE TITLE
Layout on background thread?

### ISSUE THREAD

**Issue by AttwellBrian** [facebook/TextLayoutBuilder#20]
Is code like the below thread safe?

```
Layout layout = new TextLayoutBuilder()
    .setTextAppearance(context, resId)
    .setText("TextLayoutBuilder makes life easy")
    .setWidth(400)
    .layout();
```

My understanding is that Litho does background layout and measurement. And Litho uses TextLayoutHelper under the hood for some things. So I'm wondering if this library can be used to write a custom view that does all its measurement and layout on a background thread (assuming I already know max size).

**Comment by xiphirx** [comment]
To my knowledge yes, that code can be run on a background thread and be safe. All it does internally is create a `Layout`.

**Comment by vinc3m1** [comment]
See `createTextLayout` function in Litho, which is static and intended to run on any thread:
https://github.com/facebook/litho/blob/5dd4fcd5a8d1e06ad45e93e2af774c1f44d429a1/litho-widget/src/main/java/com/facebook/litho/widget/TextSpec.java#L550-L558

**Comment by AttwellBrian** [comment]
> To my knowledge yes, that code can be run on a background thread and be safe. All it does internally is create a Layout.

Awesome. There isn't any concern about the thread safety of reading from the resource and context in the following line `setTextAppearance(context, resId)`

**Comment by vinc3m1** [comment]
I was thinking that too, but I don't see a `setTextAppearance` function on [TextLayoutBuilder](https://github.com/facebook/TextLayoutBuilder/blob/master/library/src/main/java/com/facebook/fbui/textlayoutbuilder/TextLayoutBuilder.java), or any reference to Context at all actually.

**Comment by xiphirx** [comment]
The builder takes in already resolved values. We don't query `Resources` directly unless you use `ResourceTextLayoutHelper`, which will resolve values before passing them to the builder. The README seems to be wrong / outdated. I'll go ahead and fix that...
