### ISSUE TITLE
Set alignment is not work

### ISSUE THREAD

**Issue by jack24254029** [facebook/TextLayoutBuilder#21]
I use library 1.2.0.
The alignment always is _ALIGN_NORMAL_
This is my [code](https://gist.github.com/jack24254029/8fca3c9080d207bc0290f66a1600aa72).
![screenshot_20180131-103849](https://user-images.githubusercontent.com/13265628/35602396-0e61c3b4-0673-11e8-8e93-d8ba211fbc53.png)

And I see the setTextAppearance(context, resId) in [website](https://facebook.github.io/TextLayoutBuilder/) , but I can't use in TextLayoutBuilder.

Thank you.

**Comment by xiphirx** [comment]
I don't think that the alignment isn't working, but rather your text layout's width is the exact width of the text, so there's nothing to center. If you increase the width of your layout, then you should see that it is aligned properly.

**Comment by jack24254029** [comment]
I got it.
Thank you.
