### ISSUE TITLE
Gradle fails to resolve version 1.3.1

### ISSUE THREAD

**Issue by eduardvasilache** [facebook/TextLayoutBuilder#25]
Hello!

Maybe this is intentional but.. did someone forget to upload version 1.3.1?

The readme, the website and the commits say the latest version is 1.3.1, but I get `Failed to resolve: com.facebook.fbui.textlayoutbuilder:textlayoutbuilder:1.3.1` when I try to sync my project.

Thanks!

**Comment by xiphirx** [comment]
Oops, looks like you're right! Sorry, I must have forgotten to upload the artifacts. Will put them up shortly.

**Comment by xiphirx** [comment]
Alright, I've released 1.3.1 on GH and have uploaded the artifacts to sonatype. It will take a bit of time before the artifacts are propagated to jcenter, etc and are usable. Thanks again for noticing!

**Comment by eduardvasilache** [comment]
Thanks @xiphirx !
Now I see that both 1.3.1 and 1.4.0 are uploaded.
Unfortunately, StaticLayoutProxy is still at 1.3.0:
Failed to resolve: com.facebook.fbui.textlayoutbuilder:staticlayout-proxy:1.3.1.
